"""changed column name

Revision ID: 47126b1615b3
Revises: 38e8d4fd714c
Create Date: 2021-03-07 00:40:45.324724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47126b1615b3'
down_revision = '38e8d4fd714c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
