"""Initial Migration

Revision ID: c1eddbb043a2
Revises: ff856fea8a12
Create Date: 2021-03-03 13:29:19.709624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1eddbb043a2'
down_revision = 'ff856fea8a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###
